[package]
name = "plotters-dioxus"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
plotters = { version = "0.3", default_features = false }
plotters-backend = "0.3"